### PR TITLE
Fixes #763

### LINKED ISSUE #763: Annotations that reference multiple classes are not correctly exposed as part of the public ABI
**Plugin version**
1.12.1-SNAPSHOT

**Gradle version**
7.4.2

**Describe the bug**
If an annotation references multiple types the plugin does not consider them as part of the abi.

For example given the following annotations:
```java
@Target(ElementType.TYPE)
public @interface MyJavaSingleAnnotation {
    Class<?> clazz();
}

@Target(ElementType.TYPE)
public @interface MyJavaMultipleAnnotation {
    Class<?>[] clazz() default {};
}

class InnerClassJ {}

@MyJavaSingleAnnotation(clazz = InnerClassJ.class)
public class MyCoolJavaSingleClassInA {}

@MyJavaMultipleAnnotation(clazz = {
        InnerClassJ.class, MyCoolJavaSingleClassInA.class
})
public class MyCoolJavaClassInA {}
```
And kotlin code
```kotlin
@Target(AnnotationTarget.CLASS)
annotation class MyKotlinAnnotationSingle(
    val clazz: KClass<*>
)

@Target(AnnotationTarget.CLASS)
annotation class MyKotlinAnnotationMultiple(
    val clazz: Array<KClass<*>>,
)

class InnerClass {}

@MyKotlinAnnotationSingle(InnerClass::class)
class MyCoolSingleClassInA {}

@MyKotlinAnnotationMultiple([InnerClass::class, MyCoolClassInA::class])
class MyCoolClassInA {}
```

The public-abi file generated looks as follows:
```
cat module-a/build/reports/dependency-analysis/main/abi-dump.txt 
@Lkotlin/Metadata;
public final class InnerClass {
        public fun <init> ()V
}

@Lcom/test/MyKotlinAnnotationMultiple;
@Lkotlin/Metadata;
public final class MyCoolClassInA {
        public fun <init> ()V
}

@Lcom/test/MyKotlinAnnotationSingle;
@LInnerClass;
@Lkotlin/Metadata;
public final class MyCoolSingleClassInA {
        public fun <init> ()V
}

@Lcom/test/MyJavaMultipleAnnotation;
public class com/test/MyCoolJavaClassInA {
        public fun <init> ()V
}

@Lcom/test/MyJavaSingleAnnotation;
@Lcom/test/InnerClassJ;
public class com/test/MyCoolJavaSingleClassInA {
        public fun <init> ()V
}
```

Notice that the multiple annotations (in both java and kotlin) do not correctly reference the two classes that are used within them while the single one does.

**To Reproduce**
I've attached a sample project that reproduces the issue.

[sample-dep-analysis-bug.zip](https://github.com/autonomousapps/dependency-analysis-android-gradle-plugin/files/9308852/sample-dep-analysis-bug.zip)

**Expected behavior**
We would expect the following abi file to be outputted. Notice that the Multiple* annotations now correctly reference all the classes that are utilized.
```
@Lkotlin/Metadata;
public final class InnerClass {
	public fun <init> ()V
}

@Lcom/test/MyKotlinAnnotationMultiple;
@LInnerClass;
@LMyCoolClassInA;
@Lkotlin/Metadata;
public final class MyCoolClassInA {
	public fun <init> ()V
}

@Lcom/test/MyKotlinAnnotationSingle;
@LInnerClass;
@Lkotlin/Metadata;
public final class MyCoolSingleClassInA {
	public fun <init> ()V
}

@Lcom/test/MyJavaMultipleAnnotation;
@Lcom/test/InnerClassJ;
@Lcom/test/MyCoolJavaSingleClassInA;
public class com/test/MyCoolJavaClassInA {
	public fun <init> ()V
}

@Lcom/test/MyJavaSingleAnnotation;
@Lcom/test/InnerClassJ;
public class com/test/MyCoolJavaSingleClassInA {
	public fun <init> ()V
}
```

**Additional context**
It seems like the root cause of the bug is
```kotlin
anno.values.orEmpty().filterIsInstance<Type>().forEach { type ->
      types.add(type.descriptor)
    }
```
annotation values can also be of type `ArrayList<*>` which might then contain references to the types. PR incoming.

### PR DESCRIPTION
**Pull request by FredLoh**
If an annotation references multiple types they are not correctly exposed as part of a module's public ABI. This is because we filter for an annotation values to only include a single `Type`. However annotations may have a value of type `ArrayList<*>` which can contain references to other classes.

This patch updates the `List<AnnotationNode>?.annotationTypes()` method to correctly handle the above scenario and adds some unit tests for it.

### CODE REVIEW

File: src/main/kotlin/com/autonomousapps/internal/utils/regex.kt [hunk 1]
```diff
@@ -24,8 +24,14 @@ internal fun List<AnnotationNode>?.annotationTypes(): Set<String> {
...
     types.add(anno.desc)
-    anno.values.orEmpty().filterIsInstance<Type>().forEach { type ->
-      types.add(type.descriptor)
+
+    anno.values.orEmpty().filter {
+      it is Type || it is ArrayList<*>
+    }.forEach { value ->
+      when (value) {
+        is Type -> types.add(value.descriptor)
+        is ArrayList<*> -> value.filterIsInstance<Type>().forEach { type -> types.add(type.descriptor) }
```
Comment (autonomousapps) [inline src/main/kotlin/com/autonomousapps/internal/utils/regex.kt:33]: Just checking, could this be a `List<List<...>>`?

Also, must it be an `ArrayList`? Why not just `List`?

File: src/test/kotlin/com/autonomousapps/internal/utils/RegexKtTest.kt [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+
+
+class AnnotationNodeExtensionTest {
+
+  @Test fun `should correctly parse an annotation node that references a list of Types`() {
+    val annotationNode = AnnotationNode("Lcom/test/AnnotationWithMultipleReferences;")
+    annotationNode.values = mutableListOf()
+    annotationNode.values.add(
+      arrayListOf(
+        "a string element that should be filtered",
```
Comment (autonomousapps) [inline src/test/kotlin/com/autonomousapps/internal/utils/RegexKtTest.kt:16]: could you say "filtered out" instead? `filter` usually implies _filtering in_.

File: src/test/kotlin/com/autonomousapps/internal/utils/RegexKtTest.kt [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+        Type.getType("Lcom/test/AReferencedClass;"),
+        Type.getType("Lcom/test/AnotherOne;")
+      )
+    )
+
+    val annotationTypes = listOf(annotationNode).annotationTypes()
+    Truth.assertThat(annotationTypes).hasSize(3)
```
Comment (autonomousapps) [inline src/test/kotlin/com/autonomousapps/internal/utils/RegexKtTest.kt:23]: nit: static import `assertThat`

**Review by autonomousapps — COMMENTED** [review]
Thanks so much for this PR! Left a couple of questions, but it looks really good and I look forward to merging it.

File: src/main/kotlin/com/autonomousapps/internal/utils/regex.kt (hunk 1 above)
Comment (FredLoh) [reply src/main/kotlin/com/autonomousapps/internal/utils/regex.kt:33]: The type comes through as `ArrayList`. A naive check for `List` fails but I can cast and check if it succeeds as an option?

File: src/main/kotlin/com/autonomousapps/internal/utils/regex.kt [hunk 4]
```diff
@@ -24,8 +24,14 @@ internal fun List<AnnotationNode>?.annotationTypes(): Set<String> {
 
   forEach { anno ->
     types.add(anno.desc)
-    anno.values.orEmpty().filterIsInstance<Type>().forEach { type ->
-      types.add(type.descriptor)
+
+    anno.values.orEmpty().filter {
+      it is Type || it is ArrayList<*>
```
[the remark this answers is not in the document]
Comment (FredLoh) [reply src/main/kotlin/com/autonomousapps/internal/utils/regex.kt:29]: Kept since it matches previous code style

**Review by FredLoh — COMMENTED** [review]
Will wait for a response then upload a commit with the fixes.

**Comment by FredLoh** [comment]
Sorry for the delay on the response, was on PTO 😄

**Comment by autonomousapps** [comment]
> Sorry for the delay on the response, was on PTO 😄

No need to apologize! This is OSS, timing is always best-effort 🙃

File: src/main/kotlin/com/autonomousapps/internal/utils/regex.kt (hunk 1 above)
Comment (autonomousapps) [reply src/main/kotlin/com/autonomousapps/internal/utils/regex.kt:33]: I'm just wondering if there's some guarantee that it's always an `ArrayList`. For obvious reasons I prefer to use a more general type whenever possible.

Comment (FredLoh) [reply src/main/kotlin/com/autonomousapps/internal/utils/regex.kt:33]: Ah I see. Yeah you're right, List work's here and matches what ASM expects: https://asm.ow2.io/javadoc/org/objectweb/asm/tree/AnnotationNode.html#values

**Comment by FredLoh** [comment]
Should we run the workflow's on these? I can fix any failures that result

**Comment by autonomousapps** [comment]
> Should we run the workflow's on these? I can fix any failures that result

I don't know why it keeps asking me to do that 🤦

**Comment by FredLoh** [comment]
> > Should we run the workflow's on these? I can fix any failures that result
> 
> I don't know why it keeps asking me to do that 🤦

I guess they're afraid I'll start opening hundreds of PR's to mine crypto 🗑️

**Review by autonomousapps — APPROVED** [review]

**Comment by autonomousapps** [comment]
Thanks for your contribution!
