### PR TITLE
Use code gen for moshi adapters instead of reflection

### LINKED ISSUE #667: NoSuchMethodError: kotlinx.metadata.jvm.KotlinClassHeader.<init>
**Build scan link**
Unfortunately, due to security restrictions I am not allowed to run build scans on the project with which I can reproduce the issue. I've yet to reproduce it with a minimal test project.

**Plugin version**
0.77.0 - 1.5.0

**Gradle version**
7.4.2

**(Optional) Android Gradle Plugin (AGP) version**
N/A, server-side JVM app.

**Describe the bug**
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myproject:graphViewMain'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147)
[...]
Caused by: java.lang.NoSuchMethodError: 'void kotlinx.metadata.jvm.KotlinClassHeader.<init>(java.lang.Integer, int[], java.lang.String[], java.lang.String[], java.lang.String, java.lang.String, java.lang.Integer)'
	at dev.zacsweers.moshix.sealed.reflect.MetadataMoshiSealedJsonAdapterFactoryKt.header(MetadataMoshiSealedJsonAdapterFactory.kt:153)
	at dev.zacsweers.moshix.sealed.reflect.MetadataMoshiSealedJsonAdapterFactoryKt.access$header(MetadataMoshiSealedJsonAdapterFactory.kt:1)
	at dev.zacsweers.moshix.sealed.reflect.MetadataMoshiSealedJsonAdapterFactory.create(MetadataMoshiSealedJsonAdapterFactory.kt:57)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:262)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:74)
	at com.squareup.moshi.CollectionJsonAdapter.newLinkedHashSetAdapter(CollectionJsonAdapter.java:65)
	at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:40)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:262)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
	at com.squareup.moshi.AdapterMethodsFactory$3.bind(AdapterMethodsFactory.java:214)
	at com.squareup.moshi.AdapterMethodsFactory.create(AdapterMethodsFactory.java:67)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:145)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:105)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:79)
	at com.autonomousapps.tasks.GraphViewTask.action(GraphViewTask.kt:191)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[...]
```

**To Reproduce**
1. `.\gradlew buildHealth`

**Expected behavior**
An insanely great dependency analysis report.

**Additional context**

```
.\gradlew buildEnvironment

classpath
+--- com.autonomousapps.dependency-analysis:com.autonomousapps.dependency-analysis.gradle.plugin:1.2.0
|    \--- com.autonomousapps:dependency-analysis-gradle-plugin:1.2.0
|         +--- org.jetbrains.kotlin:kotlin-bom:1.5.31
|         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31
|         |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.5.31
|         |    |    +--- org.jetbrains:annotations:13.0
|         |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31
|         |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.5.31 (*)
|         +--- com.squareup.moshi:moshi:1.12.0
|         |    +--- com.squareup.okio:okio:2.10.0
|         |    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.4.20 -> 1.5.31 (*)
|         |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.4.20 -> 1.5.31
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.31 -> 1.5.31 (*)
|         +--- com.squareup.moshi:moshi-kotlin:1.12.0
|         |    +--- com.squareup.moshi:moshi:1.12.0 (*)
|         |    +--- org.jetbrains.kotlin:kotlin-reflect:1.4.31 -> 1.5.31
|         |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.5.31 (*)
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.31 -> 1.5.31 (*)
|         +--- com.squareup.moshi:moshi-adapters:1.12.0
|         |    +--- com.squareup.moshi:moshi:1.12.0 (*)
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.4.31 -> 1.5.31 (*)
|         +--- dev.zacsweers.moshix:moshi-sealed-runtime:0.14.1
|         |    +--- com.squareup.moshi:moshi-adapters:1.12.0 (*)
|         |    +--- com.squareup.moshi:moshi:1.12.0 (*)
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30 -> 1.5.31 (*)
|         +--- dev.zacsweers.moshix:moshi-sealed-metadata-reflect:0.14.1
|         |    +--- dev.zacsweers.moshix:moshi-sealed-runtime:0.14.1 (*)
|         |    +--- org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.3.0
|         |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.5.0 -> 1.5.31 (*)
|         |    +--- com.squareup.moshi:moshi:1.12.0 (*)
|         |    +--- com.squareup.moshi:moshi-adapters:1.12.0 (*)
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30 -> 1.5.31 (*)
|         +--- org.jetbrains.kotlin:kotlin-reflect:1.5.31 (*)
|         +--- org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.3.0 (*)
|         +--- com.github.ben-manes.caffeine:caffeine:3.0.4
|         |    +--- org.checkerframework:checker-qual:3.18.0
|         |    \--- com.google.errorprone:error_prone_annotations:2.9.0
|         \--- com.google.guava:guava:31.0.1-jre
|              +--- com.google.guava:failureaccess:1.0.1
|              +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|              +--- com.google.code.findbugs:jsr305:3.0.2
|              +--- org.checkerframework:checker-qual:3.12.0 -> 3.18.0
|              +--- com.google.errorprone:error_prone_annotations:2.7.1 -> 2.9.0
|              \--- com.google.j2objc:j2objc-annotations:1.3
```

```
.\gradlew --version

------------------------------------------------------------         
Gradle 7.4.2                                                         
------------------------------------------------------------         
                                                                     
Build time:   2022-03-31 15:25:29 UTC                                
Revision:     540473b8118064efcc264694cbcaa4b677f61041               
                                                                     
Kotlin:       1.5.31                                                 
Groovy:       3.0.9                                                  
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.15 (Eclipse Adoptium 11.0.15+10)                  
OS:           Windows 10 10.0 amd64
```

### PR DESCRIPTION
**Pull request by ZacSweers**
Faster runtime performance plus it should resolve #667 along the way.

Couldn't use moshi-ir due to the low kotlin version here (it only supports Kotlin 1.6+) and lucked out that the first stable version of KSP happened to be the version of Kotlin this uses.

### CODE REVIEW

File: src/main/kotlin/com/autonomousapps/model/intermediates/producers.kt [hunk 1]
```diff
@@ -20,6 +21,7 @@ internal interface DependencyView<T> : Comparable<T> where T : DependencyView<T>
  * nb: Deliberately does not implement [DependencyView]. For various reasons, this information gets embedded in
  * [ExplodedJar], which is the preferred access point for deeper analysis.
  */
+@JsonClass(generateAdapter = true)
```
Comment (ZacSweers) [inline src/main/kotlin/com/autonomousapps/model/intermediates/producers.kt:24]: This class is also used in serialization but wasn't annotated before, not sure if there's others but they'll need to be updated with this too unless you want to just defensively keep the reflection adapter

Comment (autonomousapps) [reply src/main/kotlin/com/autonomousapps/model/intermediates/producers.kt:24]: Just in general, why do some additional data classes and enum classes now need this annotation?

Comment (ZacSweers) [reply src/main/kotlin/com/autonomousapps/model/intermediates/producers.kt:24]: since it's an annotation processor, it needs an annotation to process to know what to generate for. It also ends up being valuable for seeing at-a-glance which classes are relevant for JSON parsing, including enums. It's particularly useful in R8/proguard situations too as there are embedded rules to keep these.

**Comment by ZacSweers** [comment]
I think I got 'em all

File: build.gradle.kts [hunk 2]
```diff
@@ -8,6 +8,7 @@ plugins {
   id("org.jetbrains.kotlin.jvm")
   `kotlin-dsl`
   groovy
+  id("com.google.devtools.ksp") version "1.5.31-1.0.0"
```
Comment (autonomousapps) [inline build.gradle.kts:11]: Would I remove this plugin once this todo was resolved?
```
// TODO switch to moshi-kotlin-codegen (where this was upstreamed to) once updated to Moshi 1.13.0
```

Comment (ZacSweers) [reply build.gradle.kts:11]: Nope you would just switch the Moshi-KSP dep below with mainline Moshi code gen instead. Though if you can go to kotlin 1.6 in that case, you could replace this with Moshi-IR instead and remove KSP all together

**Review by autonomousapps — APPROVED** [review]
Thanks! I think this is for the best, to make the serialization model more explicit.
